// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3M5GP3V6REjpIurqQ7L7GWCMgVuC3Cl4',
    appId: '1:271950561801:web:0ebe38fa629a365b662ed8',
    messagingSenderId: '271950561801',
    projectId: 'saver-sis23',
    authDomain: 'saver-sis23.firebaseapp.com',
    storageBucket: 'saver-sis23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKe5I14GAVs1z84K_DbuegMn6UZEGIvhA',
    appId: '1:271950561801:android:e613411bb94085d0662ed8',
    messagingSenderId: '271950561801',
    projectId: 'saver-sis23',
    storageBucket: 'saver-sis23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD_h1Ar0iR-cgcV12e3jQ4BoBrfeleJcU',
    appId: '1:271950561801:ios:c4c4676e8f4b4ae8662ed8',
    messagingSenderId: '271950561801',
    projectId: 'saver-sis23',
    storageBucket: 'saver-sis23.appspot.com',
    iosBundleId: 'com.sis23.saver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD_h1Ar0iR-cgcV12e3jQ4BoBrfeleJcU',
    appId: '1:271950561801:ios:2cead3e23b51e45a662ed8',
    messagingSenderId: '271950561801',
    projectId: 'saver-sis23',
    storageBucket: 'saver-sis23.appspot.com',
    iosBundleId: 'com.sis23.saver.RunnerTests',
  );
}
